### ISSUE TITLE
[Feature] Create Functionality for inventory

### ISSUE THREAD

**Issue by lolzone13** [swciitg/mern_hacktober_2022#1]
- Make a create (POST) API for the inventory model.
- Test and document the API using markdown

**Comment by iks1** [comment]
Can you assign this to me ?

**Comment by ghimanshi** [comment]
Can I work on this?

**Comment by lolzone13** [comment]
sure, you can work on this @ghimanshi

**Comment by prosper20** [comment]
Hello can I get a role in the server side please ?
