### ISSUE TITLE
Create the header component

### ISSUE THREAD

**Issue by dkgoutham** [swciitg/mern_hacktober_2022#4]
<img width="704" alt="Screenshot 2022-10-07 at 1 48 24 AM" src="https://user-images.githubusercontent.com/75137173/194411781-d6977925-2eab-4036-8d82-123bb3ba50bf.png">

See the Figma file link given in the readme file for the design of the header.

**Comment by OgunmisiM** [comment]
Can this issue be released to me.

**Comment by subashpaul** [comment]
plz assign this to me

**Comment by dkgoutham** [comment]
I have assigned this issue to both of you @OgunmisiM and @subashpaul

**Comment by subashpaul** [comment]
Raised PR#6

**Comment by subashpaul** [comment]
Raised PR #6
